### ISSUE TITLE
Add quickumls and update spacy

### ISSUE THREAD

**Issue by Angelakeke** [drivendataorg/snomed-ct-entity-linking-runtime#11]
1. When I first clone the environment from here, the spacy version is 3.7.2 and I built code upon this. However,  when I tested the code on the platform, the version changed to 3.6.1. I notice this is because the last issue which is the installation of scispacy. Can you help to update the spacy version back?
2. Can you help add quickumls?    link: https://github.com/Georgetown-IR-Lab/QuickUMLS

**Comment by chrisjkuch** [comment]
> When I first clone the environment from here, the spacy version is 3.7.2 and I built code upon this. However, when I tested the code on the platform, the version changed to 3.6.1. I notice this is because the last issue which is the installation of scispacy. Can you help to update the spacy version back?

I apologize for the inconvenience that the spaCy version downgrade has caused.

Given the amount of time remaining in the competition, we are unable to revert spaCy to 3.7.2. **My strong recommendation to you is to re-train your models using spaCy 3.6.1 so your submission is compatible with the competition runtime environment**. If efforts to retrain your models fail because of the version difference, please follow up with us and we can explore possible alternative approaches.

> Can you help add quickumls?

We will not support adding QuickUMLS to the runtime image because installing QuickUMLS requires a UMLS license which we have not obtained (and which is granted only to individuals, not to groups or organizations). We are currently in the process of reviewing the UMLS license to see whether it complies with the competition rules and we will communicate our decision shortly.

**Comment by Angelakeke** [comment]
Indeed, the change in version has caused another dependency package to malfunction. I have tried many methods but cannot resolve it.😭

**Comment by chrisjkuch** [comment]
Can you provide a little more information about the conflict? The packages in the current runtime environment should be pinned at mutually compatible versions - are you trying to use a different package not currently in the environment?

**Comment by Angelakeke** [comment]
Oh, I found the problem. I could change my code to fit the environment change! thx~

**Comment by chrisjkuch** [comment]
An update on UMLS:

We determined that UMLS is not provided under an OSI-approved open-source license. Submissions that leverage libraries requiring software dependent on a UMLS license will be ineligible for prizes.
